### ISSUE TITLE
ERROR - dependencies not found

### ISSUE THREAD

**Issue by brodyFlannigan** [OneBusAway/docker#17]
Hey folks,

I'm trying to deploy[ OBA v.2 via Docker](https://github.com/OneBusAway/onebusaway-docker) and it seems some dependencies don't exist on [http://repo.obaweb.org:8080/archiva/repository/releases/](url)
Please see the screenshot below for the full error log:
![image](https://user-images.githubusercontent.com/46612183/80400224-80706200-8888-11ea-86aa-93e0b0550031.png)

If you know how I could fix this, please let me know!

**Comment by barbeau** [comment]
@dudebrains01 I believe the PR I have open here should fix this:
https://github.com/OneBusAway/onebusaway-application-modules/pull/250

Let me see if we can get that merged...

**Comment by brodyFlannigan** [comment]
> @dudebrains01 I believe the PR I have open here should fix this:
> [OneBusAway/onebusaway-application-modules#250](https://github.com/OneBusAway/onebusaway-application-modules/pull/250)
> 
> Let me see if we can get that merged...

Great. Let me know when it's done and I'll give it a shot via Docker

**Comment by barbeau** [comment]
@dudebrains01 Ok, master branch should be updated and should build now.

**Comment by brodyFlannigan** [comment]
@barbeau Nope, the Docker Compose is still throwing the same error as before...

**Comment by barbeau** [comment]
@dudebrains01 Can you double-check which commit ID is being checked out as HEAD to make sure the newest changes are being pulled in?

**Comment by brodyFlannigan** [comment]
@barbeau **d0ae96e** is the commit ID.

**Comment by barbeau** [comment]
@dudebrains01 I mean the commit of onebusaway-application-modules that's being checked out by Docker when it's cloning the repository:
https://github.com/OneBusAway/onebusaway-application-modules

Newest commit ID is https://github.com/OneBusAway/onebusaway-application-modules/commit/5c66122666e40d6132746e130691f6e9bd615d30, and that should build without the Geotools error.

**Comment by brodyFlannigan** [comment]
I can't seem to find a way to check that...
Would you happen to know how? (if it helps i'm running debian 9)

**Comment by barbeau** [comment]
In the docker script, if you run this after the `git clone` it should show the full commit ID of the current branch:
`git describe --always --abbrev=0 --match "NOT A TAG"`

See https://stackoverflow.com/a/48844915/937715

Note that you'll need to make sure that your Docker instance is re-cloning or at least fetching new commits from https://github.com/OneBusAway/onebusaway-application-modules, otherwise you won't get the latest commit that fixes the issue.

So, I'd suggest starting from scratch to make sure this is happening.

**Comment by brodyFlannigan** [comment]
Thanks.

It doesn't match.
Mine says d`0ae96e7497f073224af676401cf94863fd75d08`
I am looking into the whole docker not fetching properly thing right now.

**Comment by brodyFlannigan** [comment]
I got the new commit to fetch.
Still having problems with #14  please continue discussion there.

Closing issue.
